// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SawitProRecruitment/UserService/usecase (interfaces: UsecaseInterface)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=interfaces.mock.gen.go -package=usecase . UsecaseInterface
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	types "github.com/SawitProRecruitment/UserService/types"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecaseInterface is a mock of UsecaseInterface interface.
type MockUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseInterfaceMockRecorder
}

// MockUsecaseInterfaceMockRecorder is the mock recorder for MockUsecaseInterface.
type MockUsecaseInterfaceMockRecorder struct {
	mock *MockUsecaseInterface
}

// NewMockUsecaseInterface creates a new mock instance.
func NewMockUsecaseInterface(ctrl *gomock.Controller) *MockUsecaseInterface {
	mock := &MockUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecaseInterface) EXPECT() *MockUsecaseInterfaceMockRecorder {
	return m.recorder
}

// CreateEstate mocks base method.
func (m *MockUsecaseInterface) CreateEstate(arg0 context.Context, arg1, arg2 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEstate", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEstate indicates an expected call of CreateEstate.
func (mr *MockUsecaseInterfaceMockRecorder) CreateEstate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEstate", reflect.TypeOf((*MockUsecaseInterface)(nil).CreateEstate), arg0, arg1, arg2)
}

// CreateTree mocks base method.
func (m *MockUsecaseInterface) CreateTree(arg0 context.Context, arg1 string, arg2 types.Tree) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTree", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTree indicates an expected call of CreateTree.
func (mr *MockUsecaseInterfaceMockRecorder) CreateTree(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTree", reflect.TypeOf((*MockUsecaseInterface)(nil).CreateTree), arg0, arg1, arg2)
}

// GetDroneDistance mocks base method.
func (m *MockUsecaseInterface) GetDroneDistance(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDroneDistance", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDroneDistance indicates an expected call of GetDroneDistance.
func (mr *MockUsecaseInterfaceMockRecorder) GetDroneDistance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDroneDistance", reflect.TypeOf((*MockUsecaseInterface)(nil).GetDroneDistance), arg0, arg1)
}

// GetEstateByID mocks base method.
func (m *MockUsecaseInterface) GetEstateByID(arg0 context.Context, arg1 string) (types.Estate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstateByID", arg0, arg1)
	ret0, _ := ret[0].(types.Estate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEstateByID indicates an expected call of GetEstateByID.
func (mr *MockUsecaseInterfaceMockRecorder) GetEstateByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstateByID", reflect.TypeOf((*MockUsecaseInterface)(nil).GetEstateByID), arg0, arg1)
}

// GetEstateStats mocks base method.
func (m *MockUsecaseInterface) GetEstateStats(arg0 context.Context, arg1 string) (types.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstateStats", arg0, arg1)
	ret0, _ := ret[0].(types.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEstateStats indicates an expected call of GetEstateStats.
func (mr *MockUsecaseInterfaceMockRecorder) GetEstateStats(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstateStats", reflect.TypeOf((*MockUsecaseInterface)(nil).GetEstateStats), arg0, arg1)
}
